frontend/src/components/object/ObjectList.vue
frontend/src/services/objectService.ts
frontend/src/store/objectStore.ts

This won't really work until the fixes from here https://github.com/bcgov/common-object-management-service/pull/85 are in the API.

Use bucket ID for create and List

---

frontend/src/assets/main.css
frontend/src/components/bucket/BucketPermission.vue
frontend/src/components/bucket/BucketsTable.vue
frontend/src/interfaces/UserPermission.ts
frontend/src/interfaces/index.ts
frontend/src/services/bucketService.ts
frontend/src/services/userService.ts
frontend/src/store/bucketStore.ts
frontend/src/utils/constants.ts

Implements the bucket permissions modal on the bucket list view.

Bucket permissions

---

frontend/package-lock.json
frontend/package.json
frontend/src/assets/primevue.scss
frontend/src/components/bucket/BucketsTable.vue
frontend/src/components/object/ObjectList.vue
frontend/src/components/object/ObjectTable.vue
frontend/src/components/object/ObjectUpload.vue
frontend/src/components/object/ObjectUploadFile.vue
frontend/src/interfaces/COMSObject.ts
frontend/src/interfaces/Metadata.ts
frontend/src/interfaces/index.ts
frontend/src/services/objectService.ts
frontend/src/store/objectStore.ts
frontend/src/utils/formatters.ts

Adds a single or multi file object upload component, with file browser selection and drag and drop functionality. 

Object upload

---

app/config/custom-environment-variables.json
frontend/.eslintrc.cjs
frontend/src/App.vue
frontend/src/components/Login.vue
frontend/src/components/bcgov/BCGovHeader.vue
frontend/src/components/bucket/BucketList.vue
frontend/src/components/bucket/BucketPermission.vue
frontend/src/components/bucket/BucketsSidebar.vue
frontend/src/components/bucket/BucketsTable.vue
frontend/src/components/form/TextInput.vue
frontend/src/components/layout/InitApp.vue
frontend/src/components/layout/Navbar.vue
frontend/src/components/object/DeleteObjectButton.vue
frontend/src/components/object/DownloadObjectButton.vue
frontend/src/components/object/ObjectList.vue
frontend/src/components/object/ObjectSidebar.vue
frontend/src/components/object/ObjectTable.vue
frontend/src/components/object/ObjectUpload.vue
frontend/src/components/object/ObjectUploadFile.vue
frontend/src/components/object/UploadObjectButton.vue
frontend/src/main.ts
frontend/src/views/DeveloperView.vue
frontend/src/views/HomeView.vue
frontend/src/views/ListObjectsView.vue

By bumping the formatting enforcement from essential to recommended, we adopt stronger best practices on how to format our vue template code.
[SHOWCASE-2886](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2886)

Increase general vue3 linting strictness to recommended level

---

frontend/src/components/object/ObjectUpload.vue

Changes file upload structure from a queue to parallel uploads.

Parallelize file uploads

---

frontend/src/components/bucket/BucketList.vue
frontend/src/components/bucket/BucketPermission.vue
frontend/src/components/bucket/BucketsTable.vue
frontend/src/interfaces/Permission.ts
frontend/src/interfaces/User.ts
frontend/src/interfaces/UserPermission.ts
frontend/src/interfaces/UserPermissions.ts
frontend/src/interfaces/index.ts
frontend/src/services/userService.ts
frontend/src/store/bucketStore.ts
frontend/src/store/userStore.ts

Only allows IDPs with elevated rights to view permissions, and be given the manage permission on a bucket.

IDP Behaviours

---

frontend/src/services/bucketService.ts
frontend/src/services/index.ts
frontend/src/services/objectService.ts
frontend/src/services/permissionService.ts
frontend/src/store/bucketStore.ts
frontend/src/store/objectStore.ts

Ensures the object list will only show objects a user has at least one permission on.

Check users object permissions when obtaining list

---

frontend/src/store/userStore.ts

Removes any user without an associated IDP from user search results. Really just prevents the default system user from being searchable as there is no need for this.

Filter out users without an IDP

---

frontend/src/components/bucket/BucketsTable.vue
frontend/src/components/layout/Navbar.vue
frontend/src/components/object/ObjectList.vue
frontend/src/interfaces/Bucket.ts
frontend/src/router/index.ts
frontend/src/store/bucketStore.ts
frontend/src/store/index.ts
frontend/src/store/navStore.ts
frontend/src/views/ListObjectsView.vue

[f32b228](https://github.com/bcgov/bcbox/commit/f32b228b094edc5925f325de2c64f845e1fb17fa) - Show bucket permissions icon to MANAGE users only
[5b2c91d](https://github.com/bcgov/bcbox/commit/5b2c91d7a72f3bb26700af97147b871a2c5b4bb2) - Implement breadcrumb navigation

Various bug fixes

---

frontend/src/assets/main.scss
frontend/src/assets/primevue.scss
frontend/src/components/bucket/BucketPermission.vue
frontend/src/components/bucket/BucketsTable.vue
frontend/src/components/form/SearchUsers.vue
frontend/src/components/object/ObjectFileDetails.vue
frontend/src/components/object/ObjectPermission.vue
frontend/src/components/object/ObjectPermissionAddUser.vue
frontend/src/components/object/ObjectTable.vue
frontend/src/components/object/ObjectUpload.vue
frontend/src/store/bucketStore.ts
frontend/src/store/objectStore.ts
frontend/src/store/userStore.ts
frontend/src/views/ListObjectsView.vue

1. Adds user search to object permissions modal.
2. SearchUsers now accepts any UserPermissions array
3. Realigns table headers in bucket/object perm tables.
4. Removes scoped styling and relies on main.css file.
5. Updates bucket permissions function to get unique users list in a single API call

Add user search to object permissions modal

---

frontend/src/components/bucket/BucketPermission.vue
frontend/src/components/bucket/BucketsTable.vue
frontend/src/components/object/ObjectPermission.vue
frontend/src/components/object/ObjectTable.vue

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3021
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3027
Add the default column sort to objects, buckets, both permissions.
Since we're not doing any API paging, can rely on simple PrimeVue table settings.

Default table sorts

---

frontend/src/components/object/ObjectTable.vue
frontend/src/store/objectStore.ts

Added an inputSwitch component, and hooked up with togglePublic api call. The toggle button will be disabled if user isn't Manager. The switch effects the value update on db side as well.

Implementation of toggle button and set public flag

---

.codeclimate.yml
frontend/src/assets/main.scss
frontend/src/assets/primevue.scss
frontend/src/assets/variables.scss
frontend/src/components/bucket/BucketList.vue
frontend/src/components/bucket/BucketsTable.vue
frontend/src/components/object/ObjectTable.vue
frontend/src/components/object/ObjectUpload.vue
frontend/src/components/object/share/ShareObjectButton.vue

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3025
Toggle outline class of upload buttons to match mockup design. (doesn't address **all** button colors, that would be another task if we're doing that)
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2971
Align header styles with designs. Move subheader text outside so default flex centers things. Make a dialog class for global styling to apply to all dialogs of this type. 

Style tweaks

---

frontend/src/components/bucket/BucketConfigForm.vue

Fetches proper bucket list for user after adding a bucket or updating one. 

Fetch proper bucket list for user after configuring

---

frontend/src/components/object/DeleteObjectButton.vue
frontend/src/components/object/DownloadObjectButton.vue
frontend/src/components/object/ObjectList.vue
frontend/src/store/objectStore.ts

_Still need to test out a bit more but should get some feedback on implementation_
When uploading files, disable other parts of the object list page
"v2" mocks from here https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2913?
Use local field to track "file upload open" bool. Pass to any children if they are to be disabled too. If more and more components are added and they're children the disabled prop will have to keep being added if they're needing to be disabled as well.
If non-children will need to be disabled might need to to store implementation. Tried that out, it's in commit history of this PR.
Disable buttons. No global disable for datatable so use the usual no-click, opacity css trick.

disable other stuff when uploadin

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/form/SearchUsers.vue
frontend/src/components/object/DownloadObjectButton.vue
frontend/src/components/object/ObjectAccess.vue
frontend/src/components/object/ObjectFileDetails.vue
frontend/src/components/object/ObjectMetadata.vue
frontend/src/components/object/ObjectProperties.vue
frontend/src/components/object/ObjectSidebar.vue
frontend/src/components/object/ObjectTag.vue
frontend/src/interfaces/IChangeEvent.ts
frontend/src/interfaces/IInputEvent.ts
frontend/src/interfaces/index.ts
frontend/src/views/list/ListObjectsView.vue

1. Bump PrimeVue to 3.25.0
2. Clean up unnecessary network calls
3. Various bug fixes

Restructure network calls for Object sidebar & File Details

---

bcgovpubcode.yaml
frontend/src/components/object/ObjectList.vue
frontend/src/components/object/ObjectTable.vue

- added bcgovpubcode.yaml
- refresh metadata store from objectTable component (to resolve data concurrency)

Name display 

---

frontend/src/components/object/ObjectUpload.vue

Changing the text in the upload section form to align with: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3160

Changing the text in the upload section form

---

frontend/src/components/object/ObjectTable.vue
frontend/src/components/object/share/ShareObjectButton.vue
frontend/src/utils/formatters.ts
frontend/tests/unit/utils/formatters.spec.ts

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3158
Show short form UUID in table with hover for full one
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3153
Disable for public until unauthed File Details page works

More UI qa feedback fixes

---

frontend/src/components/bucket/BucketTable.vue
frontend/src/components/object/ObjectFileDetails.vue
frontend/src/components/object/ObjectList.vue
frontend/src/components/object/ObjectPermission.vue
frontend/src/components/object/ObjectSidebar.vue
frontend/src/components/object/ObjectTable.vue
frontend/src/components/object/ObjectUpload.vue
frontend/src/store/bucketStore.ts
frontend/src/store/objectStore.ts
frontend/src/store/permissionStore.ts
frontend/src/types/options/ObjectAddPermissionsOptions.ts
frontend/src/types/options/ObjectDeletePermissionsOptions.ts
frontend/src/types/options/SearchBucketsOptions.ts

Permissions audit based on document provided in SHOWCASE-3148.

Permissions audit

---

frontend/package-lock.json
frontend/package.json
frontend/src/assets/base.css
frontend/src/main.ts

Adding BCSans as the font so it's consistent with other BC Gov standards.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3157
Old look:
New look:

BCSans and new font

---

frontend/src/components/object/ObjectFileDetails.vue
frontend/src/components/object/ObjectTable.vue
frontend/src/components/object/index.ts
frontend/src/components/object/share/ShareObjectButton.vue
frontend/src/components/object/share/index.ts

Resolve circular build dependency

Resolve circular build dependency

---

frontend/src/components/layout/Navbar.vue
frontend/src/views/HomeView.vue

- Removed Developer tab from navigation. our dev's know how to manually visit the url if we need it
- add Help tab
- made navbar always show and hide individual tabs if un/auth'd

Remove Developer tab, add Help tab

---

app/config/idplist-default.json

Adds business BCeID to default IDP list

Add business BCeID to default list

---

frontend/src/components/object/ObjectTable.vue

BCBox fix for new null updatedAt fields in COMS.

Add new field to object table data source

---

frontend/src/App.vue
frontend/src/components/object/ObjectUpload.vue
frontend/src/components/object/ObjectUploadBasic.vue
frontend/src/router/index.ts
frontend/src/store/appStore.ts

During object uploads
1. shows a custom message confirmation during navigation away from upload components
2. shows a browser default confirmation during window navigation (refresh, tab close, etc)

Navigation notifications during uploads

---

frontend/src/components/object/ObjectFileDetails.vue
frontend/src/components/object/ObjectProperties.vue
frontend/src/components/object/ObjectTable.vue
frontend/src/components/object/share/ShareObjectButton.vue
frontend/src/types/COMSObject.ts
frontend/tests/unit/store/objectStore.spec.ts

Aligns BCBox with the upcoming object changes in COMS.
- Removes references to coms-name
- Adds name to COMSObject and references in place of old metadata name

Align with COMS changes

---

frontend/src/components/bucket/BucketList.vue
frontend/src/utils/constants.ts
frontend/src/views/HomeView.vue

Updates home page and bucket config text

Text updates

---

frontend/src/components/object/ObjectFileDetails.vue
frontend/src/components/object/ObjectMetadata.vue
frontend/src/components/object/ObjectMetadataTagForm.vue
frontend/src/components/object/ObjectSidebar.vue
frontend/src/components/object/ObjectTag.vue
frontend/src/components/object/ObjectUploadFile.vue
frontend/src/components/object/index.ts
frontend/src/services/objectService.ts
frontend/src/store/metadataStore.ts
frontend/src/store/objectStore.ts
frontend/src/store/tagStore.ts

Adds ability to update metadata and tags via the object details view.

Metadata and tag updating

---

README.md
frontend/src/components/object/ObjectUploadBasic.vue
frontend/src/services/objectService.ts
frontend/src/store/objectStore.ts

Adds the metadata/tag modal to the version upload workflow. Metadata and tags are automatically copied from the most recent version as defaults.

Edit metadata/tags for new version upload

---

frontend/src/components/bucket/BucketTable.vue
frontend/src/components/layout/LoginButton.vue
frontend/src/router/index.ts
frontend/src/services/authService.ts
frontend/src/services/bucketService.ts
frontend/src/store/bucketStore.ts

Adds new button to the bucket list. Clicking will present a confirm dialog with a warning message. Confirming will remove all associated data for the bucket from the COMS db. S3 bucket remains untouched. Button is not present to users without bucket DELETE permissions.

Bucket delete

---

frontend/src/components/object/ObjectTable.vue

Disables the "public" toggle for files if the user isn't an elevated (i.e. IDIR) user.
[SHOWCASE-3281](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3281)

Disable "public" toggle for files if not elevated user

---

frontend/src/components/object/ObjectTable.vue

Missing a prop to the filters. Needed for when you undo all the filtering

Use the bucket ID prop in the object filters

---

frontend/src/components/object/ObjectMetadata.vue
frontend/src/components/object/ObjectTag.vue

Hide the "Edit metadata" and "Edit tags" buttons if the user doesn't have `UPDATE` permissions.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3277
N/A

Hide "edit metadata" and "edit tags" buttons

---

frontend/src/components/bucket/BucketConfigForm.vue
frontend/src/components/bucket/BucketList.vue

This updates the text tips on the "Configure new bucket" modal.
The "Configure new bucket" button on My Buckets page has also been re-labelled to "Configure bucket to BCBox".
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3278
N/A

Text changes: configuring new buckets

---

frontend/src/components/object/ObjectVersion.vue

show version action icons depending on permissions.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3315

use objectId to check permissions for button display

---

frontend/src/utils/utils.ts

Update `utils.js` so content-disposition header submits filenames are RFC3986 compliant 
Changes suggested from MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

SC-3324, fix: update utils.js for RFC3986 compliant filenames

---

frontend/src/components/bucket/BucketConfigForm.vue
frontend/src/services/objectService.ts

- When object table loads, call COMS searchObjects api sequentially to reduce COMS db load

Search objects

---

frontend/src/components/object/ObjectFilters.vue

bug ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3351

Include bucket perms when showing objects filtered by tag/meta

---

README.md

Adds a note to the README on removing BCBox-specific branding if self-hosting.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3308
Documentation (non-breaking change with enhancements to documentation)

Update README: add note on removing BCBox-specific branding

---

Dockerfile

This commit resolves the EACCES issues we were previously encountering in and allows us to return to using alpine as our base container image. This will allow us to have more direct control over the version of node running.
[SHOWCASE-3189](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3189)

Return back to alpine node base image

---

app/src/components/utils.ts

Fix getGitRevision mishandling HEAD file read

---

frontend/src/components/object/ObjectTable.vue

This PR resolves #112.
The "select all" checkbox in the objects table now only selects items visible on the current page.
Primevue doesn't provide a native way to do this at the moment (see primefaces/primevue/issues/3477), so the solution involved figuring out what objects are on the current page.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3365
The DOM had to be directly queried as a workaround.
For the most part, the list of objects provided by `DataTable`'s `value-change` emit is correctly sorted, in that it matches what's currently displayed in the table.
However, this is _not_ the case on initial page load. Instead, `value-change` simply uses the order as returned by the COMS API (specifically, by `GET /object`); …

ObjectTable: select all on current page only

---

frontend/src/assets/main.scss
frontend/src/assets/variables.scss
frontend/src/components/bucket/BucketChildConfig.vue
frontend/src/components/bucket/BucketConfigForm.vue
frontend/src/components/bucket/BucketTable.vue
frontend/src/components/bucket/BucketTableBucketName.vue
frontend/src/components/bucket/index.ts
frontend/src/services/bucketService.ts
frontend/src/store/bucketStore.ts
frontend/src/utils/utils.ts

BCBox UI for adding a sub-folder to a bucket.
ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3371
ui/ux reference: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3326 (contains link to a mural board)

Add sub-folder creation support

---

Dockerfile

Copies the config folder to sbin. 

Copy config to sbin

---

frontend/src/views/HomeView.vue

Remove sync sentance from homescreen login page

---

frontend/src/components/object/ObjectFilters.vue
frontend/src/components/object/ObjectList.vue
frontend/src/components/object/ObjectTable.vue
frontend/src/services/objectService.ts
frontend/src/store/metadataStore.ts
frontend/src/store/tagStore.ts

Replace Refresh Button
Make sure data-table updates when object permissions is updated using permission box
Download works on select one and multiple files
Delete works on select one and multiple files
Upload buttons works
Select all works
Detail box works
Remove any orphan codes
[
SC3518](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3518)

Refactor filters and tags to work without objectstore

---

frontend/src/components/object/ObjectFilters.vue
frontend/src/components/object/ObjectList.vue
frontend/src/components/object/ObjectProperties.vue
frontend/src/components/object/ObjectTable.vue
frontend/src/services/objectService.ts
frontend/src/store/bucketStore.ts
frontend/src/store/metadataStore.ts
frontend/src/store/objectStore.ts
frontend/src/store/tagStore.ts
frontend/src/types/options/ObjectSearchPermissionsOptions.ts
frontend/src/types/options/SearchObjectsOptions.ts
frontend/src/views/list/ListObjectsView.vue

- Lazy-load COMS data into object table; pagination 
ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3467
- dataTable callbacks for filter/sort/search to re-load COMS data
ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3517
- fetch object permissions and populate in store during lazy-load process
- fix object filters 

Object table: lazy-loading, filtering, sorting and fetching permissions

---

frontend/src/components/common/InviteButton.vue
frontend/src/services/inviteService.ts

- add READ, UPDATE, CREATE Checkbox permissions to bucket invite links
- Add READ, UPDATE checkbox permissions to files invite links
- READ is default
[SHOWCASE-3643](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3643)

Add permCodes and checkbox options

---

frontend/src/components/bucket/BucketChildConfig.vue
frontend/src/components/bucket/BucketList.vue
frontend/src/components/bucket/BucketTable.vue
frontend/src/components/common/InviteButton.vue
frontend/src/components/common/SyncButton.vue

Add keyboard event to trigger when 'enter' is pressed on any bucket list action button.
[SC3571](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3571)

Add enter key event

---

frontend/src/components/bucket/BucketChildConfig.vue
frontend/src/components/bucket/BucketConfigForm.vue
frontend/src/components/bucket/BucketList.vue
frontend/src/components/bucket/BucketSidebar.vue
frontend/src/components/bucket/BucketTable.vue
frontend/src/components/bucket/BucketTableBucketName.vue
frontend/src/components/common/InviteButton.vue
frontend/src/components/common/SyncButton.vue
frontend/src/components/layout/Navbar.vue
frontend/src/components/object/ObjectProperties.vue
frontend/src/router/index.ts
frontend/src/utils/constants.ts
frontend/src/utils/utils.ts
frontend/src/views/HomeView.vue
frontend/src/views/invite/InviteView.vue
frontend/src/views/list/ListObjectsView.vue
frontend/tests/unit/components/bucket/BucketSidebar.spec.ts
frontend/tests/unit/components/layout/Navbar.spec.ts

Replace term bucket with folder
Reformat folder name in folder list
Change invite button terminology

Bucket Terminology changes

---

.github/environments/values.dev.yaml
.github/environments/values.prod.yaml
.github/environments/values.test.yaml
app/config/custom-environment-variables.json
charts/bcbox/Chart.yaml
charts/bcbox/README.md
charts/bcbox/templates/deploymentconfig.yaml
charts/bcbox/values.yaml

Add environment variables
Update Helm charts and OCP templates to prepare for CHES integration

Configure Environments for backend and Changes

---

frontend/src/components/object/ObjectTable.vue

Fix sorting order using updated date

---

frontend/src/components/bucket/BucketChildConfig.vue
frontend/src/components/common/Invite.vue
frontend/src/components/common/ShareButton.vue
frontend/src/components/object/ObjectMetadata.vue
frontend/src/components/object/ObjectTable.vue
frontend/src/lib/primevue/index.ts
frontend/src/services/inviteService.ts

Updates to the file/folder invite form
- use vee-validate composition api to validate form fields
- add multi-email input
- remove 'open' invites (not scoped to a user)
tickets: 
- https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3673
-  https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3676
- ux ref: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3630 (see screenshot '3 - Multi invite'))
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3673

Use vee-validate for Invite form; multi-user invites

---

frontend/src/store/permissionStore.ts

we previously removed the process of patching permission data
in the store when switching contexts of the app. As a result,
when opening the perms modal, we replaced perms in the store with just perms for the current resource in the modal..
causing table of objects/bucksts in background to not have permission data, both while modal is visible and after modal is closed.
To fix this, much as we dislike the patch process handled by some utils functions.. and we were also calling it incorrectly in the past (typo).. we can use it again in the short term.

Restore permission store patch process

---

frontend/src/components/bucket/BucketPermission.vue
frontend/src/components/bucket/BucketTable.vue
frontend/src/components/common/Invite.vue

add help text for invite form
additional bug-fix: require READ perm for bucket sync
ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3696

Make READ perm optional for folder invites

---

frontend/src/components/object/ObjectTable.vue
frontend/src/components/object/ObjectVersion.vue

- Replace 'updateAt' with 'lastModifiedDate' in object list
- Replace 'cratedAt' with 'lastModifiedDate' in version list

Repalce update date for an object listing with lastModifiedDate

---

frontend/src/components/bucket/BucketConfigForm.vue
frontend/src/components/common/SyncButton.vue
frontend/src/services/bucketService.ts
frontend/src/store/bucketStore.ts
frontend/src/store/objectStore.ts
frontend/src/views/list/ListObjectsView.vue

- when viewing contents of a folder (object list), trigger folder sync if required
- show toast alerts
- invoke toast from sync button component instead of store 

Trigger event-driven folder sync

---

.github/workflows/zap.yaml

feat(CI): zap scan for bcbox

---

frontend/src/components/bucket/BucketPermission.vue
frontend/src/components/common/BulkPermission.vue
frontend/src/components/common/Invite.vue
frontend/src/services/inviteService.ts
frontend/src/services/permissionService.ts
frontend/src/store/permissionStore.ts
frontend/src/types/options/BucketDeletePermissionsOptions.ts
frontend/src/views/list/ListObjectsView.vue

Folder permission changes are now recursive (cascading to all subfolders for which current user has MANAGE permission)
- passing additional recursive parameter to COMS
- added alert
- additional commit to only trigger auto-sync when current user has READ permission

Recursive permission actions

---

bcgovpubcode.yaml
frontend/src/assets/main.scss
frontend/src/components/bucket/BucketList.vue
frontend/src/components/bucket/BucketPermissionAddUser.vue
frontend/src/components/bucket/BucketTable.vue
frontend/src/components/common/BulkPermission.vue
frontend/src/components/form/SearchUsers.vue
frontend/src/components/layout/Navbar.vue
frontend/src/lib/primevue/index.ts
frontend/src/store/authStore.ts
frontend/src/store/permissionStore.ts
frontend/src/store/userStore.ts
frontend/src/views/HomeView.vue
frontend/tests/unit/components/layout/Navbar.spec.ts

- [Default to sub claim for unconfigured identity providers](https://github.com/bcgov/bcbox/commit/0a89a5fc99bcae2bc15a31571e739c0a371ac669)
- [Modfy User Search to handle additional IDP's](https://github.com/bcgov/bcbox/commit/d04ae45a7dc14321bb7a26097160112811929d49)
- [Wording changes to support BCSC idp](https://github.com/bcgov/bcbox/pull/239/commits/368e2f640c3b0812cb8b69601a3b51e13d1c8a4d)
Breaking change (fix or feature that would cause existing functionality to change)

Changes to support BCSC auth

---

frontend/src/services/bucketService.ts

The "My Files" page calls `GET /bucket` to retrieve bucket details. This COMS API call is now split into multiple calls if the full URL (i.e. endpoint + `?bucketId[]=xxxx` + `&bucketId[]=yyyy` + ...) exceeds 2,000 characters. 
Firefox supports a maximum of 65,536 characters in an URL, but Chromium (i.e. Chrome, Edge etc.) only supports 2,083. If the user has access to a large number of buckets, the `GET /bucket` URL can easily exceed these limits and result in errors.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-4047
The URL splitting logic was largely borrowed from [`objectService.searchObjects()`](https://github.com/bcgov/bcbox/blob/ecd0d89b6196baf88d2164c4ebab3b55232ba97e/frontend/src/services/objectService.ts#L246).
In this PR, …

"My Files" page: split GET /bucket API calls into multiple if resulting URL is too long
