frontend/src/components/Login.vue, frontend/src/components/layout/Navbar.vue, frontend/src/router/index.ts, frontend/src/services/interceptors.ts, frontend/src/store/authStore.ts, frontend/src/utils/constants.ts, frontend/src/views/DeveloperView.vue, frontend/src/views/HomeView.vue
Computed properties tied to the Keycloak object seem to not update no matter what I do... so the token getter is still returning the original token even though the refresh loop is going fine and getting a new token into the Keycloak object.
If we just expose the Keycloak object itself as a getter and then reference its properties in components that works fine though.
So for now we should just live with this to get the refresh token and other Keycloak property access working as expected.
Or maybe it's fine to have the one object exposed, it's TypeScript now and it's typed so it's not like you can reference things that aren't there or wouldn't work...
Can come back to later as well and try some more.
=> Make refresh token work

frontend/src/router/index.ts, frontend/src/store/authStore.ts, frontend/src/utils/constants.ts
Redirect to login if route needs it. Add options to login call if want to use, but not needed with this pattern yet.
The page blinks in before the redirect (if first navigation is a secured route and keycloak is not already inited) which I never like but will think on that later...
=> Navigation gaurd

frontend/src/assets/base.css, frontend/src/store/bucketStore.ts
Axios removes null/empty set parameters automatically. In the event a user had no permissions the app was mistakenly searching for all buckets and displaying them to the user.
=> Resolve Axios removing null/empty set param

frontend/src/components/object/ObjectList.vue, frontend/src/components/object/ObjectPermission.vue, frontend/src/components/object/ObjectTable.vue, frontend/src/interfaces/UserPermissions.ts, frontend/src/services/objectService.ts, frontend/src/services/permissionService.ts, frontend/src/store/bucketStore.ts, frontend/src/store/objectStore.ts
Allow users to set object permissions on files they have manage permissions for. The "Add User" part is on an upcoming ticket.
Don't show the actions on a file that you don't have the corresponding permission for.
Additionally a fix for
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3012
There's probably some efficiencies that can be done here. This is mostly the same code as the bucket permissions screen and table, but with enough changes I couldn't quickly figure out how to generalize it. There's some differences between the 2 things. 
Possibly could be refactored to a common component and/or composable, but need to be sure the behavior would stay the same.
At the very least the component SCSS should be extracted out so …
=> Object Permissions

frontend/src/store/bucketStore.ts, frontend/src/store/objectStore.ts
Ensures proper permissions are shown in the bucket/object permissions table after either successfully updating or encountering an error.
=> Show correct bucket/object permissions after updating

frontend/src/components/form/GridRow.vue, frontend/src/components/object/DeleteObjectButton.vue, frontend/src/components/object/DownloadObjectButton.vue, frontend/src/components/object/ObjectAccess.vue, frontend/src/components/object/ObjectFileDetails.vue, frontend/src/components/object/ObjectList.vue, frontend/src/components/object/ObjectProperties.vue, frontend/src/components/object/ObjectSidebar.vue, frontend/src/components/object/ObjectTable.vue, frontend/src/components/object/ObjectUpload.vue, frontend/src/components/object/ObjectUploadFile.vue, frontend/src/components/object/index.ts, frontend/src/interfaces/COMSObject.ts
- Adds bucket information to object properties screen
- Adds action buttons to object properties screen
- Sidebar object details no longer displays all the information
- Adds back the 'Manage by' information
=> Add missing information to object details screens

frontend/src/components/bucket/BucketList.vue, frontend/src/components/bucket/BucketTable.vue, frontend/src/components/form/SearchUsers.vue, frontend/src/components/object/ObjectAccess.vue, frontend/src/components/object/ObjectFileDetails.vue, frontend/src/components/object/ObjectList.vue, frontend/src/components/object/ObjectMetadata.vue, frontend/src/components/object/ObjectProperties.vue, frontend/src/components/object/ObjectTable.vue, frontend/src/components/object/ObjectTag.vue, frontend/src/components/object/share/ShareObjectButton.vue, frontend/src/services/objectService.ts, frontend/src/store/bucketStore.ts, frontend/src/store/metadataStore.ts, frontend/src/store/objectStore.ts, frontend/src/store/permissionStore.ts, frontend/src/store/tagStore.ts, frontend/src/store/userStore.ts, frontend/src/types/options/SearchObjectsOptions.ts, frontend/src/views/DeveloperView.vue, frontend/src/views/list/ListObjectsView.vue
Ensures user has proper rights and permissions to action certain bucket management functionality.
=> Lock down bucket management to proper permissions

frontend/src/components/object/ObjectFileDetails.vue
Missed setting the style on the File Details > Object Permissions dialog
We really should refactor this to a ObjectPermissionsButton component since it's used in 2 places, we don't need to be doing "hey here's the button, clicking the button does this, here's the dialog, the dialog contains this component" twice. But leaving that for the immediate term since I see tickets in progress about file permissions, and the file details page, so let's avoid possible merge conflict right now.
=> Add missing style on file details object permissions

frontend/src/App.vue, frontend/src/components/guards/RequireAuth.vue, frontend/src/components/guards/RequirePublicOrAuth.vue, frontend/src/components/guards/index.ts, frontend/src/components/object/ObjectFileDetails.vue, frontend/src/components/object/ObjectTable.vue, frontend/src/components/object/share/ShareObjectButton.vue, frontend/src/router/index.ts, frontend/src/services/objectService.ts, frontend/src/store/objectStore.ts, frontend/src/utils/constants.ts, frontend/src/views/Forbidden.vue, frontend/src/views/detail/DetailObjectsView.vue, frontend/src/views/list/ListObjectsView.vue
- Adds a 403 Forbidden page
- Does a permissions check on object list and file details route entry, moves to a Forbidden page if necessary.
- Resolves a bug with the BCBox share link
- Share button now requires READ permission
Bug fix (non-breaking change which fixes an issue) 
=> Route entry permission checking

frontend/src/components/object/ObjectFileDetails.vue, frontend/src/components/object/ObjectProperties.vue
Resolve 422 error loading object file details view.
=> Resolve 422 loading object file details

frontend/src/assets/base.css, frontend/src/assets/main.scss, frontend/src/components/bucket/BucketSidebar.vue, frontend/src/components/form/GridRow.vue, frontend/src/components/object/ObjectAccess.vue, frontend/src/components/object/ObjectFileDetails.vue, frontend/src/components/object/ObjectMetadata.vue, frontend/src/components/object/ObjectProperties.vue, frontend/src/components/object/ObjectSidebar.vue, frontend/src/components/object/ObjectTag.vue, frontend/src/components/object/ObjectUploadFile.vue, frontend/src/views/list/ListObjectsView.vue
- fixes layout issues where object or bucket name overruns the screen and doesnt wrap to two lines.
- datatables have font-size 16px, set to 15px to match custom default set in body.
- I found some other css/display issues that we'll need to get fixed separately
=> Wrap object and bucket name heading

frontend/src/components/bucket/BucketConfigForm.vue, frontend/src/components/form/Password.vue, frontend/src/components/form/TextInput.vue
Modified configure bucket form to support new labels/placeholders/helptext/mandatory described in https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3103. Changed custom common 'InputText' and 'Password' vue components to support helpText rendering. Removed 'Key' from validation schema, it's not mandatory anymore.
=> Provide clarity on the Create Bucket screen

frontend/src/components/object/ObjectUpload.vue, frontend/src/services/interceptors.ts, frontend/src/services/objectService.ts, frontend/src/store/objectStore.ts
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3139? Changed the number of milliseconds before timing out the request for file upload only, to infinitive. Adding timeout as input argument at service/store layer, if not passed in defaults to 10000ms.
Used 1GB for testing.
=> Changing request timeout to infinite for file upload

frontend/src/components/object/ObjectTable.vue, frontend/src/lib/primevue/index.ts
Implementation of (in-memory, primevue table) file search. Use primevue filter from https://primevue.org/datatable/#filter
(note there's a current Typescript bug that they keep trying to fix without success, see comment in code)
case-insensitive 'contains' string search using name column only. This could be expanded to other columns if desired
Handles the truncation alright as well
Not sure if this is the exact UX/placement for this, could adjust but looks fine to me. Maybe check with Tyler.
Could remove darker background and/or borders
Also add object list refresh button while we're at it next to search.
=> Proposal: File search, object refresh

frontend/src/components/bucket/BucketConfigForm.vue, frontend/src/components/form/TextInput.vue, frontend/src/types/Bucket.ts, frontend/src/utils/utils.ts
Creates a form differential so COMS only receives the modified bucket information for updates.
=> Check bucket exists before create/update

frontend/src/views/HomeView.vue
Caps the images on the home page to the max width of their container to prevent spillage.
Minor wording adjustments.
=> Home page: cap image size

frontend/src/components/object/ObjectPermission.vue
Prevents removal of the last manager of an object when unticking their READ permission.
=> Prevent removal of last manager when unticking READ

frontend/src/components/bucket/BucketList.vue, frontend/src/utils/constants.ts
Advise bucket creators to contact IDIM team regarding BCeID users
ticket 2943: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2943:
"Update the Bucket configure modal to articulate Disclaimer for bucket admins wanting to share with BCeID users must be added to tell them they must consult with IDIM prior to offering sharing to BCeID users"
=> Add notice on Configure Bucket form

app/package-lock.json, app/package.json, charts/bcbox/Chart.yaml, charts/bcbox/README.md, frontend/package-lock.json, frontend/package.json, frontend/src/components/object/ObjectFileDetails.vue, frontend/src/components/object/ObjectProperties.vue, frontend/src/components/object/ObjectTable.vue, frontend/src/components/object/share/ShareObjectButton.vue
This change is needed to align with COMS v0.4.2 where the metadata for the name field will now use the key `coms-name` instead of `name`.
Breaking change (fix or feature that would cause existing functionality to change)
=> BCBox v0.2.1 - Retarget metadata name to coms-name

frontend/src/components/object/DeleteObjectButton.vue, frontend/src/components/object/DownloadObjectButton.vue, frontend/src/components/object/ObjectAccess.vue, frontend/src/components/object/ObjectFileDetails.vue, frontend/src/components/object/ObjectMetadata.vue, frontend/src/components/object/ObjectUploadBasic.vue, frontend/src/components/object/ObjectVersion.vue, frontend/src/components/object/index.ts, frontend/src/composables/useAlert.ts, frontend/src/lib/primevue/useToast.ts, frontend/src/services/objectService.ts, frontend/src/store/objectStore.ts, frontend/src/views/detail/DetailObjectsView.vue
Allows specific object versions to be downloaded and deleted.
=> Version downloading/deleting

frontend/src/components/object/ObjectMetadataTagForm.vue, frontend/src/components/object/ObjectUpload.vue, frontend/src/components/object/ObjectUploadFile.vue, frontend/src/services/objectService.ts, frontend/src/store/objectStore.ts, frontend/src/utils/constants.ts, frontend/tests/unit/store/objectStore.spec.ts
Allows the user to attach metadata and tags (up to 9, to allow coms-id), via a modal form prior to object upload.
=> Metadata & tags on upload

frontend/src/components/bucket/BucketConfigForm.vue, frontend/src/utils/constants.ts, frontend/src/utils/utils.ts
New key handling during bucket configuration. Per discussion BCBox has converged on
Key = undefined -> send w/o key; COMS defaults to /
Key = foo/bar -> send as foo/bar
Key = /foo/bar -> send as foo/bar
=> Update key handling during bucket config

frontend/src/components/form/Password.vue, frontend/src/components/form/TextInput.vue
(fork for this one-liner, don't have contributor any more/again yet)
Randomly noticed this on help texts on fields
`${name}-help`
Added the v-bind needed to the attribute. So it's not treating it as a string in HTML, but a JS template literal.
=> ID attribute on help texts not resolving field name

frontend/src/components/bucket/BucketPermission.vue, frontend/src/components/bucket/BucketSidebar.vue, frontend/src/components/object/ObjectAccess.vue, frontend/src/components/object/ObjectPermission.vue, frontend/src/store/permissionStore.ts
- Resolves an issue where bucket sidebar was showing every user in the store with manage instead of the requested bucket.
- Also shifted the permission tables to use OnBeforeMount to marginally speed up data loading
=> Bucket sidebar shows correct 'Managed By' users

frontend/src/components/object/ObjectSidebar.vue, frontend/src/components/object/ObjectTable.vue
Do not load the metadata on the Object list page until it's needed (sidepane open).
Add metadata fetch on the object ID in the sidepane prop watch same as tagging.
=> Remove eager metadata fetch on object list

frontend/src/services/objectService.ts, frontend/src/utils/utils.ts
Update BCBox to use new API for COMS.
Change createObject and updateObject methods to use PUT instead of POST
Upload as octet-stream
Breaking change (fix or feature that would cause existing functionality to change)
Made an assumption that objects passed to objService will be of `File` type.
=> SC-3303: Align BCBox with V0.6 file upload changes

frontend/src/services/objectService.ts, frontend/src/store/objectStore.ts, frontend/tests/unit/store/objectStore.spec.ts
ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3330
to load the objects table, if there are more than about 50 objects some browsers will show errors, because the COMS request url contains so many `objectId`'s and is too long.
In object search service function, i have split into multiple requests, each time, passing an acceptable number of the `objectId`'s
=> Divide COMS object search request to limit URL length

frontend/src/services/objectService.ts
Prevent loading large files into browser memory before upload. In objectService.ts
Requesting someone upload a large (>5 GB file) and ensure that file is not loaded into browser memory.
=> SC-3335, bug: stop loading files into browser memory before upload

frontend/src/services/objectService.ts, frontend/src/store/bucketStore.ts, frontend/src/store/metadataStore.ts, frontend/src/store/objectStore.ts, frontend/src/store/permissionStore.ts, frontend/src/store/tagStore.ts, frontend/src/store/userStore.ts, frontend/src/store/versionStore.ts
- disable pinia store persistence to browser's local storage
- Do not pass file name in Content-Disposition header when adding a new version of an object
=> Dont pass file name when updating an object, dont persist store

frontend/src/components/object/ObjectProperties.vue, frontend/src/components/object/ObjectTable.vue
- evaluate bucket permissions when refreshing object list (ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3328?)
- previously, if you visited the file details page, the bucket name is missing from the 'properties' section. because people might navigate straight to this page (via a share link) we need to fetch the bucket details.
=> Fix object list refresh; get bucket details

frontend/src/services/userService.ts, frontend/src/utils/constants.ts
With recent change to COMS where new objects are 'created by' 'system user' (https://github.com/bcgov/common-object-management-service/pull/211)
We found errors in bcbox when searching for details of that user when 
- showing who owns the file on the file details page
- listing who has object permissions
these errors were caused by searching for the 'system user' in COMS.
A quick fix is to filter out the system user from searches.
future work should address the ux where 'created by' and 'updated by' may now appear blank for new records after a sync.
=> Filter out system user from COMS user search

frontend/src/components/bucket/BucketConfigForm.vue, frontend/src/utils/utils.ts
Fixing joinPath util so it doesn't return undefined when a single slash is input.
Fixing BucketConfigForm.vue so empty strings returned by joinPath don't add issues with bucket creation.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3338
=> SC-3338, fix: prevent single slash in BucketConfigForm error

frontend/src/components/common/SyncButton.vue
This PR fixes a bug where the bucket name in the sync modal isn't updated, if the bucket name was updated after page load.
Previously, the bucket name was fetched when `onMounted` - it's now been moved to when the sync button is clicked instead.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3353
N/A
=> Update bucket name in sync modal after page load

Dockerfile, frontend/src/assets/main.scss, frontend/src/assets/primevue.scss, frontend/src/components/bucket/BucketConfigForm.vue, frontend/src/components/object/ObjectAccess.vue, frontend/src/components/object/ObjectFileDetails.vue, frontend/src/components/object/ObjectMetadata.vue, frontend/src/components/object/ObjectProperties.vue, frontend/src/components/object/ObjectSidebar.vue, frontend/src/components/object/ObjectTable.vue, frontend/src/components/object/ObjectTag.vue, frontend/src/components/object/ObjectVersion.vue, frontend/src/lib/primevue/index.ts, frontend/src/services/userService.ts
ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3347
and a mix of other minor changes:
- Show more accurate details for versions
- show incrementing version number
- await user search when showing created by details
- show createdAt or updatedAt depending on bucket versioning
- Fix user search to filter SYSTEM_USER
- Properties panel to always show object-level attributes
- no longer show version-specific created/updated by/dates
- for each version.
- Hide Access heading if no object-level manage perm exists
- Pass bucketId to Tag/Meta components for permission check
- Revert primary button hover style changes
- remove hyperlink from tags
- Fix text formatting on bucket config form
- Change object table sort to 'updated date' descending
- Bump base red-hat image for docker …
=> Make Object / Version dates more accurate

frontend/src/components/bucket/BucketList.vue, frontend/tests/unit/components/bucket/BucketConfigForm.spec.ts, frontend/tests/unit/components/bucket/BucketList.spec.ts, frontend/tests/unit/components/bucket/BucketPermission.spec.ts, frontend/tests/unit/components/bucket/BucketPermissionAddUser.spec.ts, frontend/tests/unit/components/bucket/BucketSidebar.spec.ts, frontend/tests/unit/components/bucket/BucketTable.spec.ts, frontend/tests/unit/components/layout/Footer.spec.ts, frontend/tests/unit/components/layout/Navbar.spec.ts, frontend/tests/unit/components/layout/ProgressLoader.spec.ts, frontend/tests/unit/components/layout/Spinner.spec.ts
For ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3320
Added a few frontend component tests. 
Test for layout components:
-Footer
-Navbar
-ProgressLoader
-Spinner
Tests for bucket components:
-BucketConfigForm
-BucketList
-BucketPermission
-BucketPermissionAddUser
-BucketSidebar
-BucketTable
Not all tests are fully complete for the above files, will need more work to improve coverage.
=> feat:(SC-3320) Added tests for layout components and bucket components

frontend/src/assets/primevue.scss, frontend/src/components/bucket/BucketList.vue, frontend/src/components/bucket/BucketSidebar.vue, frontend/src/components/object/ObjectAccess.vue, frontend/src/components/object/ObjectFileDetails.vue, frontend/src/components/object/ObjectMetadata.vue, frontend/src/components/object/ObjectMetadataTagForm.vue, frontend/src/components/object/ObjectProperties.vue, frontend/src/components/object/ObjectSidebar.vue, frontend/src/components/object/ObjectTag.vue, frontend/src/components/object/ObjectVersion.vue, frontend/src/views/DeveloperView.vue, frontend/src/views/Forbidden.vue, frontend/src/views/HomeView.vue, frontend/src/views/NotFound.vue, frontend/src/views/oidc/OidcCallbackView.vue, frontend/src/views/oidc/OidcLoginView.vue, frontend/src/views/oidc/OidcLogoutView.vue
Removed, adjust and reuse heading tags.
This should fix reported formatting issue to login/logout page and other unreported inconsistency.
We have to make sure all headings are being displayed properly in terms of size and location on screen.
This should fix login/logout and other inconsistency caused by adjusting heading tags.
=> adjust and remove heading css

frontend/src/services/userService.ts
Resolves a bug caused by assigned an undefined array to a new set. This caused an empty array parameter to be sent to COMS during user searches, somehow resulting in duplicate users in the user store.
=> Fix bug caused by assigned undefined array to new set

app/.gitignore, frontend/src/assets/primevue.scss, frontend/src/components/form/SearchUsers.vue, frontend/src/components/object/ObjectPermission.vue, frontend/src/components/object/ObjectPublicToggle.vue, frontend/src/components/object/ObjectTable.vue, frontend/src/components/object/index.ts, frontend/src/store/objectStore.ts
This PR makes the following UX improvements to the object permissions modal, as originally identified in [SHOWCASE-3331](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3331): 
* New public toggle, in addition to the existing (identical) toggle in the object table
* New "user permissions" heading above the "add user" button
* Rewording of text hint for the user search box, to avoid confusion between the *username* and user's  *name*
A bugfix on `/app/.gitignore` incorrectly ignoring `package-lock.json` (unrelated to the Jira ticket) has also been slipstreamed in.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3366
* Object permissions modal:
* Object permissions modal, …
=> Add public toggle to permissions modal

frontend/src/components/object/ObjectUploadBasic.vue, frontend/src/store/versionStore.ts
This change will display a confirmation pop up when a user tries to upload a non-version bucket file, notifying that action will replace the file and previous version will no longer be available.
=> Add clarification to version update action for non-versioned buckets

Dockerfile, app/package-lock.json, app/package.json, frontend/src/assets/primevue.scss, frontend/src/components/bucket/BucketTable.vue, frontend/src/components/bucket/BucketTableBucketName.vue, frontend/src/components/bucket/index.ts, frontend/src/lib/primevue/index.ts, frontend/src/types/BucketTreeNode.ts, frontend/src/types/index.ts, frontend/src/utils/utils.ts
Changes the bucket list view to use a TreeTable instead of a DataTable. This allows us to mimic a folder hierarchy of buckets based on their canonical path (endpoint, bucket, key). Fake folders will be inserted to create a full tree if there is no direct parent bucket available. 
This PR also slipstream resolves a build issue with the Dockerfile.
=> Implement support for nested buckets view

frontend/src/components/bucket/BucketConfigForm.vue, frontend/src/components/bucket/BucketTable.vue, frontend/src/utils/utils.ts
This PR adds an additional toast, whenever credentials are updated for a bucket that has children:
The additional toast is displayed for 10 seconds.
Although the toast asks the user if there's any child buckets, it's only displayed if there *are* child buckets managed inside COMS/BCBox.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3372
The single quotes in the toast message are conflicting with the linter:
* If escaping the single quotes within a single quote delineated string (i.e `'Don\'t forget...'`), the linter will convert it back into double quotes and remove the escape sequence (i.e. `"Don't forget..."`
* If using double quotes without escaping `\'`, it results in a linter error
=> Create toast if user updates credentials for bucket that has children

app/app.ts, app/package-lock.json, app/package.json, app/src/components/constants.ts
Implement CORS and Helmet middleware
=> Implement CORS and Helmet middleware

frontend/src/components/bucket/BucketList.vue
Quick fix for race condition between getUserId and GET /bucket, by getting the latter to poll on the user ID first.
=> Poll userId before fetching buckets list

frontend/src/components/object/DownloadObjectButton.vue, frontend/src/services/objectService.ts, frontend/src/store/objectStore.ts, frontend/tests/unit/store/objectStore.spec.ts
ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3508
Caused by the browser settings relating to pop-ups and new tabs.
- Edge: Pop-ups and redirects > on | off
- chrome: Pop-ups and redirects >
- Sites can send pop-ups and use redirects
- Don't allow sites to send pop-ups or use redirects
- Firefox: Block pop-up windows > on | off
mdn docs:
Modern browsers have strict popup blocker policies. Popup windows must be opened in direct response to user input, and a separate user gesture event is required for each Window.open() call. 
So my proposed change is to show a toast message (in case user has permanantly blocked popups and arent aware of the cause). To allow for this, the window.open() is now invoked in the component.
- Move window.open event to the vue component
Bug fix …
=> Skip pop-up blocker

frontend/src/components/bucket/BucketSidebar.vue, frontend/src/components/common/SyncButton.vue, frontend/src/components/object/ObjectProperties.vue, frontend/src/types/Bucket.ts, frontend/src/types/COMSObject.ts, frontend/vite.config.ts
The last sync date for objects and buckets is now displayed in the following places:
* Objects
* "File details" page (but not in the sidebar)
* Sync modal
* Buckets
* "My buckets" page, in the sidebar
* Sync modal
In the backend DB, objects have a `lastSyncedDate` while buckets have `lastSyncRequestedDate` - both are displayed as "last sync date" in BCBox for brevity.
In some cases, the last sync date is not available (i.e. it has a value of `null` in the backend DB because it hasn't been synced after sync date tracking was implemented):
* **Sync modal:** ~~"N/A"~~ *"(none)" is displayed instead*
* **"File details" page:** last sync date is omitted entirely (including the "last sync date" text)
* **"My buckets" sidebar**: ~~a blank space is displayed next to "last sync date"~~ *"(none)" …
=> Display last sync date for buckets and objects

frontend/src/assets/main.scss, frontend/src/components/bucket/BucketTable.vue, frontend/src/components/common/InviteButton.vue, frontend/src/components/common/index.ts, frontend/src/components/object/ObjectFileDetails.vue, frontend/src/components/object/ObjectTable.vue, frontend/src/router/index.ts, frontend/src/services/index.ts, frontend/src/services/inviteService.ts, frontend/src/services/permissionService.ts, frontend/src/types/InviteCreateOptions.ts, frontend/src/types/index.ts, frontend/src/utils/constants.ts, frontend/src/views/invite/InviteView.vue, frontend/tests/unit/components/invite/InviteView.spec.ts
=> Implement Magic Link redirection support and InviteButton component

frontend/src/store/bucketStore.ts
When login using BCedID all buckets are seems to be showing up, this will restrict fetch only if buckets Ids are provided.
[
SC3610](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3610)
=> Restrict bucket fetch only if Ids are provided

frontend/src/components/common/InviteButton.vue
Change the text in the invite link modal, to make it clear that links are single-use.
Original wording:
> Invite someone using an invite link
New wording:
> Invite someone using an invite link - the links are single-use; you must generate a new link for each user you intend to send this to
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3611
Documentation (non-breaking change with enhancements to documentation)
N/A
=> Invite link modal: clarify that links are single-use

.github/CODEOWNERS, frontend/src/components/object/ObjectUpload.vue, frontend/src/store/objectStore.ts, frontend/tests/unit/store/objectStore.spec.ts
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3549
- Catch COMS error and show toast at component level 
- Simplify fileUpload template
Bug fix (non-breaking change which fixes an issue) 
- [] I have checked that unit tests pass locally with my changes
=> Show correct file upload status

frontend/src/components/bucket/BucketTable.vue, frontend/src/components/common/InviteButton.vue
show Invite feature requires MANAGE
Hide the Invite feature for an object or bucket that current user doesnt have MANAGE perm for.
This is a requirement of the COMS api so the feature wont work.. .hide if not functional
=> Show Invite button requires MANAGE

frontend/src/components/common/InviteButton.vue
This fixes the `aria-label` for the "object share" button for objects, so that screen readers can correctly read the button.
There were no issues with the visible tooltip.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3653
Much of the heavy lifting for this ticket seems to have been already done in [SHOWCASE-3656](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3656) and [SHOWCASE-3657](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3657) (and possibly [SHOWCASE-3515](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3515), when Primevue got updated to 3.52)
* See #189 and #188
=> Fix object share button aria-label

frontend/src/components/object/ObjectPermission.vue, frontend/src/components/object/ObjectPermissionAddUser.vue, frontend/src/store/permissionStore.ts
When adding a user to the object permissions, READ permissions are now also added.
The READ permission checkbox has also been disabled, as this is the "minimum" permission level. If the user wants to remove READ permissions for a user, they can do so by removing the user entirely using the red "remove" button for the user.
This allows us to reduce COMS API calls and therefore lag in the UI (see "further comments" at bottom).
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3664
Previously, toggling any of the permissions forces a check on the READ permission and vice versa, since READ is a prerequisite for all of the others. This resulted in additional COMS API calls, resulting in glitchy/delayed checkbox behaviour as it waits for …
=> Object permissions: auto-add READ permissions when adding user

frontend/src/components/object/ObjectPermission.vue, frontend/src/components/object/ObjectPublicToggle.vue, frontend/src/components/object/ObjectTable.vue
Setting the "set to public" switch to "on" (in both the object table and file permissions modal) now opens an additional modal that asks the user to confirm before doing so:
(this dialog is only displayed when toggling a file from private to public)
A toast is then displayed: 
A toast is also displayed when toggling a file from public to private:
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3667
N/A
=> Display confirmation dialog and toasts on toggling file to public

app/app.ts, app/package-lock.json, app/package.json, app/src/components/constants.ts, app/src/controllers/email.ts, app/src/interfaces/IExpress.ts, app/src/middleware/authentication.ts, app/src/middleware/validation.ts, app/src/routes/v1/index.ts, app/src/services/email.ts, app/src/types/CurrentUser.ts, app/src/types/Email.ts, app/src/types/index.ts, app/src/validators/common.ts, app/src/validators/email.ts, app/src/validators/index.ts, charts/bcbox/Chart.yaml, frontend/src/components/common/InviteButton.vue, frontend/src/services/interceptors.ts, frontend/src/services/inviteService.ts, frontend/src/utils/emailTemplates.ts
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3598
Enable email notification for invites.
- when scoping invite, email invitee
- only show invite url for open invites (a feature soon to be retired)
- call CHES api via the server-side/backend of BCBox
- authenticate request from browser to bcbox backend api using authorization middleware
- authenticate call to CHES with client credentials
- use CHES email merge feature
note: For some reason the deployment config didnt get updated .. so i have manually edited it for the PR deployment only.
=> Send invite in email notification

frontend/src/components/object/ObjectTable.vue
when loading object table, after fetching objects we fetch object permissions.
If folder is empty and there are no objects, the call to fetch object permissions searches perms for all objects in entire COMS db.
=> Bug fix: only fetch permissions for objects in table

frontend/src/assets/main.scss, frontend/src/components/common/ShareButton.vue
- Can tab all elements
- focus does not goes out of the dialog
- Focus goes back to the button when exit model
[SC3658](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3658?)
=> Add keyboard navigation to Share Model

frontend/src/components/bucket/BucketChildConfig.vue, frontend/src/components/bucket/BucketConfigForm.vue, frontend/src/components/form/TextInput.vue, frontend/src/views/list/ListObjectsView.vue
When adding adding a sub-folder, allow user to enter a path that traverses multiple folder levels.
- [x ] I have checked that unit tests pass locally with my changes
=> Allow child bucket sub-path to contains forward slashes

frontend/src/assets/main.scss, frontend/src/components/bucket/BucketPermission.vue, frontend/src/components/bucket/BucketTable.vue, frontend/src/components/form/SearchUsers.vue, frontend/src/components/object/ObjectPermission.vue, frontend/src/components/object/ObjectPublicToggle.vue, frontend/src/components/object/ObjectTable.vue, frontend/src/store/navStore.ts, frontend/src/utils/utils.ts
- Make folder and file permissions keyboard accessible
- Make permission table keyboard and screen able accessible
- Focus back to the button element when model is closed
- Add aria tags for screen reader
- Make content in model screen reader friendly
- Keep focus in the model so outside DOM elements are not available
=> Add tab navigation and aria labels for permissions model

frontend/src/components/bucket/BucketChildConfig.vue, frontend/src/components/bucket/BucketTable.vue
Fix tab order, start from entire popup, heading and end with close button
Focus should go back to the config button when hit closed
Focus should stay in the open dialog box
[SC3685](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3685)
=> Tab Navigation for Child configuration model

frontend/src/assets/variables.scss, frontend/src/components/common/BulkPermissionResults.vue
This PR adds a `DataTable` (contained inside a modal) displaying the results of a bulk operation (i.e. add/remove permissions, sending invites). This is displayed after the user clicks "Submit" and all operations are complete.
Each operation is displayed as one of 3 possible result types:
* Success (green checkmark) - operation was successful
* No action (grey minus sign) - no action was performed (e.g. permission already exists on user)
* Failure (red "X") - fail (see "further comments" at bottom)
The actual bulk operations were implemented in #212, though the results weren't displayed in a user-friendly table.
The contents of this `DataTable` can also be downloaded as a CSV file.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3677 …
=> Show results of bulk invite and add/remove in table

frontend/src/components/common/BulkPermissionResults.vue
This tweaks the styling of the "save results" button icon for the bulk results modal, so that it matches the style throughout the rest of BCBox (i.e. blue icon with no background). Previously, it was a white icon on a blue button.
This also removes the unneeded argument in `exportCSV()`, as mentioned in https://github.com/bcgov/bcbox/pull/215#discussion_r1644943689.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3679
In the interest of time, #215 was pushed to production without these fixes. The current PR is a minor continuation and includes them.
=> Bulk results modal: change "save results" icon to match BCBox style

frontend/src/components/bucket/BucketConfigForm.vue, frontend/src/components/bucket/BucketList.vue, frontend/src/components/bucket/BucketTable.vue, frontend/src/components/common/ShareButton.vue
- Tab Navigation for Config folder
- Focus fixes for share and config buttons
- added aria labels
[SC3686](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3686)
=> Tab Navigation for configure folder

app/src/controllers/email.ts, app/src/validators/email.ts, frontend/src/components/common/BulkPermission.vue, frontend/src/components/common/BulkPermissionResults.vue, frontend/src/components/common/Invite.vue, frontend/src/services/inviteService.ts, frontend/src/utils/emailTemplates.ts, frontend/src/utils/formatters.ts
For the share feature, also notify existing users where result is just a permission update.
ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3702
For the share feature, also notify existing users where result is just a permission update.
=> Notify exsting users with invite

frontend/src/components/bucket/BucketSidebar.vue, frontend/src/components/bucket/BucketTable.vue, frontend/src/components/common/SyncButton.vue, frontend/src/components/object/ObjectSidebar.vue, frontend/src/components/object/ObjectTable.vue
- Folder detail tab navigation
- Sync button tab navigation
[SC3688](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3688)
=> Add Tab Navigation to sidebar

frontend/src/components/bucket/BucketTable.vue, frontend/src/components/object/DeleteObjectButton.vue
Focus should be the entire popup box and it should read out entire content
Focus should go back to the details icon button once close is hit
[
SC3689](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3689)
=> Add Navigation to Delete button

frontend/src/components/common/BulkPermission.vue, frontend/src/components/common/BulkPermissionResults.vue
This fixes the styling for the bulk results modal/table.
Previously:
* Long email/results strings would wrap
* Spacing was inadequate along the right side of the results column
* The table/modal would be to narrow if the results string for all emails is short 
Also, the `DataTable`'s `export-filename` declaration was too lengthy, so it has been moved to a separate line.
N/A
=> Bulk results modal: tweak DataTable styling

frontend/src/components/object/ObjectList.vue, frontend/src/components/object/ObjectUpload.vue
- Upload button tab navigation
- Delete button tab navigation
- Download button tab navigation
[SC3690](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3690)
=> Add Tab Navigation to upload button

frontend/src/components/object/ObjectUpload.vue, frontend/src/store/objectStore.ts
allow file upload process to create new version of file if it exists
=> allow file upload process to create new version of file if it exiists

.github/actions/deploy-to-environment/action.yaml, .github/workflows/on-pr-closed.yaml
This adds an additional GitHub Actions step for installing `oc`.
The `ubuntu-latest` GitHub Actions image no longer includes `oc` out of the box, so it must now be explicitly installed.
*More info:* https://github.com/actions/runner-images/issues/10636
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3816
N/A
=> GitHub Actions: explicitly install oc first

frontend/src/components/bucket/BucketConfigForm.vue, frontend/src/components/bucket/BucketTable.vue, frontend/src/components/common/SyncButton.vue, frontend/src/components/object/ObjectVersion.vue, frontend/src/services/bucketService.ts, frontend/src/store/bucketStore.ts, frontend/src/types/Version.ts, frontend/tests/unit/store/versionStore.spec.ts
- Trigger recursive sync when connecting a new storage location
- Minimal implementation of the COMS recursive sync feature. When user connects a new storage location, trigger a sync. More advanced progress indicator and 'auto-syncing' to follow in a future commit.
- Do a recursive delete when deleting a folder (bucket)
this will require COMS pr 297 to be merged first)
=> Recursive bucket sync and delete actions

frontend/src/assets/main.scss, frontend/src/components/bucket/BucketConfigForm.vue, frontend/src/components/bucket/BucketTable.vue, frontend/src/components/common/SyncButton.vue, frontend/src/components/object/DeletedObjectTable.vue, frontend/src/components/object/ObjectTable.vue
- Add recursive options to the syncButton component
- add syncButton to the bucketConfigForm
=> Recursive sync button

frontend/src/App.vue, frontend/src/components/bucket/BucketConfigForm.vue, frontend/src/components/common/BulkPermission.vue, frontend/src/components/common/Invite.vue, frontend/src/components/common/SyncButton.vue, frontend/src/components/object/DeleteObjectButton.vue, frontend/src/components/object/ObjectMetadataTagForm.vue, frontend/src/components/object/ObjectPublicToggle.vue, frontend/src/components/object/ObjectUpload.vue, frontend/src/components/object/ObjectUploadBasic.vue, frontend/src/components/object/RestoreObjectButton.vue, frontend/src/store/bucketStore.ts, frontend/src/store/metadataStore.ts, frontend/src/store/objectStore.ts, frontend/src/store/permissionStore.ts, frontend/src/store/tagStore.ts, frontend/src/store/userStore.ts, frontend/src/store/versionStore.ts, frontend/src/views/invite/InviteView.vue, frontend/src/views/list/ListObjectsView.vue, frontend/tests/unit/store/bucketStore.spec.ts, frontend/tests/unit/store/metadataStore.spec.ts, frontend/tests/unit/store/objectStore.spec.ts, frontend/tests/unit/store/tagStore.spec.ts, frontend/tests/unit/store/userStore.spec.ts, frontend/tests/unit/store/versionStore.spec.ts
The detailed COMS error response message (specifically, the `detail` field) is now displayed in the toast body instead. Previously, only the HTTP response code and a generic `AxiosError` message is displayed.
**Example:** updating a bucket using invalid S3 credentials
_Before:_
> **Error: Configuring storage location source**
> AxiosError: Request failed with status code 409
_After:_
> **Error: Configuring storage location source**
> Unable to validate supplied credentials for the bucket 
Also, error notifications no longer disappear automatically; they must be closed manually instead.
This should make it easier for users to diagnose basic errors, without having to reach out to us every time.
[SHOWCASE-3941](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3941)
New feature …
=> Error toasts: show HTTP response detail + don't auto-close
